# Generated by Django 5.1.1 on 2024-10-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
