# Generated by Django 5.1.1 on 2024-10-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_estudiante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
